services:
  web:
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27019:27017"
volumes:
  mongodb_data: